# Generated by Django 5.2.3 on 2025-06-26 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_watchlist_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"ordering": ["-added_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "listing")},
        ),
        migrations.AddField(
            model_name="watchlist",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="category",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="image",
        ),
    ]
