# Generated by Django 5.2.3 on 2025-06-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_watchlist_listing_alter_watchlist_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listings",
            name="highest_bid",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
